language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Zc0puMP5We7ox/p/QNkOY3qsikB3CxXeMOw1tDCRM5kooMJ6GguGeNyda/dCHVT/KqI4k3ajkmMPg+wmct1F5A+1j7ink985QbsjSMRCeaawIpU/V8fSqN/IdfIx23H236Bo3oZ+GaSAdG1Ly1Tu9cZ18zV077EjqEPMt1Ygg4tOj1Fo9cySlDkF6IvieYVwoan5fMtqdkmapFbywBo/+sP12HN1qNLVUUQ+Rw2zgWYFasVs6jFPW03lCSo2uMev62noAhKfhCoNyKd1wwFzXQgqvraS19V1z5qmLDTKhmyrNTuT7VZHwHBzrBo6Yn4nHgbTLptzV3+QHYx6OhO5XQ+BiWMQljqQgT1YfEB6vBMcpMMhfaPMTUHPF/LLAEo1Ldq0TEmhr6bL2f/y+tlbBz59QvgO/my97SPWVSYQNQffS/mXiH/dG0hPJFD1qt15cfqdOm+ZlzoBemLYyZ5g2fPp7T4y1vvj1fAQYlYxam4BxRZ8lgALequS1tDKkVoQOERCrXE/7wgfJbfNBn9Qie1SavvQebq3vzki8EuscFStMyqckCu+/fy8d2laYNGKiQzwxS8dfrrzdHMBTKQQfTzFVTSK2qnV/mpN/oEWQJ4mjKRBOkmsUd7Q6IM6Ic+DAcx7g+WVe0aL7Hu7bzc6jMNajJ2wmvoE5mtmyZzRAoE=
  file:
    - "vfile-reporter.js"
    - "vfile-reporter.min.js"
  on:
    tags: true
